title: FastMarkDocs
description: Enhanced OpenAPI documentation generation from markdown files for FastAPI applications

# GitHub Pages URL configuration
# For GitHub Pages, these should match your repository settings
url: "https://danvatca.github.io"
baseurl: "/FastMarkDocs"

# Theme - Using Just the Docs with custom brand colors
remote_theme: just-the-docs/just-the-docs

# Just the Docs configuration
color_scheme: nil  # Default light theme with custom CSS overrides
favicon_ico: "/favicon.ico"

# Defaults for all pages
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "default"

# Plugins (GitHub Pages compatible)
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-remote-theme

# Just the Docs navigation is handled by nav_order in front matter

# Social links
github_username: danvatca
twitter_username: danvatca

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    block:
      line_numbers: false

# Output directory (relative to source directory)
destination: ../../docs

# Keep source directory clean - no intermediate files
keep_files: []
safe: true

# Cache and metadata settings
jekyll_cache_dir: /tmp/jekyll-cache-fastmarkdocs
metadata_file: /tmp/jekyll-metadata-fastmarkdocs

# GitHub Pages settings
repository: danvatca/FastMarkDocs

# Exclude files from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .bundle/
  - BUILD.md
  - build-docs.sh
  - Makefile.docs
  - "*.sh"
  - GITHUB_PAGES_TROUBLESHOOTING.md
  - .jekyll-cache/
  - .jekyll-metadata
  - .sass-cache/
  - _site/
  - "*.tmp"
  - "*.temp"
  - .DS_Store
  - README.md

# SEO
author:
  name: Dan Vatca
  email: dan.vatca@gmail.com

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# GitHub Pages specific settings
github: [metadata]

# Development settings (only used locally)
livereload: true
incremental: true

# Ensure proper asset handling
sass:
  style: compressed

# Timezone
timezone: UTC 