codecov:
  require_ci_to_pass: true
  notify:
    wait_for_ci: true

coverage:
  precision: 2
  round: down
  range: "90...100"
  
  status:
    project:
      default:
        target: 90%
        threshold: 0.5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error
    patch:
      default:
        target: 90%
        threshold: 0.5%
        if_no_uploads: error
        if_not_found: success
        if_ci_failed: error

comment:
  layout: "reach,diff,flags,tree,reach"
  behavior: default
  require_changes: false

github_checks:
  annotations: true 