title: FastMarkDocs
description: Enhanced OpenAPI documentation generation from markdown files for FastAPI applications
url: "https://danvatca.github.io"
baseurl: "/fastmarkdocs"

# Theme
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Navigation
header_pages:
  - getting-started.md
  - user-guide.md
  - api-reference.md
  - examples.md
  - advanced.md

# Social links
github_username: danvatca
twitter_username: danvatca

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

# GitHub Pages settings
repository: danvatca/fastmarkdocs

# Exclude files
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/
  - .bundle/
  - BUILD.md

# SEO
author:
  name: Dan Vatca
  email: dan.vatca@gmail.com

# Google Analytics (optional)
# google_analytics: UA-XXXXXXXX-X

# Development settings (only used locally)
livereload: true
incremental: true 